version: "3.9"
services:
  app:
    container_name: dev-server
    build:
      context: .
    environment:
      PORT: 8080
    volumes:
      - .:/app
    ports:
      - "18000:8080"
      - "40000:40000"
    security_opt:
      - "apparmor=unconfined"
    cap_add:
      - SYS_PTRACE
